spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: false
server:
  port: 8080
  http2:
    enabled: true
logging:
  level:
    org.axonframework: debug
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:axon
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      indent_output: true
---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/axon?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      indent_output: true
